version: "3.9"

services:
  backend:
    build: ./backend          # Dockerfile is inside ./backend
    container_name: skin_backend
    ports:
      - "8000:8000"           # host → container
    # live-reload during Python edits:
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev   
    container_name: skin_frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000   # internal Docker DNS
    volumes:
      - ./frontend:/usr/src/app          # live-reload for Next.js
    depends_on:
      - backend
